import {
  ChatDotRound,
  Checked,
  Clock,
  DataBoard,
  Files,
  FolderOpened,
  Histogram,
  Money,
  Notebook,
  OfficeBuilding,
  PieChart,
  Postcard,
  Promotion,
  SetUp,
  TrendCharts,
  User,
  Wallet,
} from '@element-plus/icons-vue';

export const iconRegistry = {
  ChatDotRound,
  Checked,
  Clock,
  DataBoard,
  Files,
  FolderOpened,
  Histogram,
  Money,
  Notebook,
  OfficeBuilding,
  PieChart,
  Postcard,
  Promotion,
  SetUp,
  TrendCharts,
  User,
  Wallet,
};

export const roleMenus = {
  employee: [
    { path: '/employee/profile', label: '个人中心', icon: 'User' },
    { path: '/employee/archive', label: '个人档案', icon: 'Postcard' },
    { path: '/employee/attendance', label: '考勤查询', icon: 'Clock' },
    { path: '/employee/payroll', label: '工资查询', icon: 'Wallet' },
    { path: '/employee/performance', label: '绩效查询', icon: 'TrendCharts' },
    { path: '/employee/applications', label: '申请中心', icon: 'Promotion' },
  ],
  manager: [
    { path: '/manager/dashboard', label: '部门首页', icon: 'DataBoard' },
    { path: '/manager/employees', label: '本部门员工', icon: 'Postcard' },
    { path: '/manager/attendance', label: '本部门考勤', icon: 'Clock' },
    { path: '/manager/performance-entry', label: '绩效录入', icon: 'Notebook' },
    { path: '/manager/approvals', label: '本部门审批', icon: 'Files' },
  ],
  hr: [
    { path: '/hr/dashboard', label: 'HR首页', icon: 'DataBoard' },
    { path: '/hr/employees', label: '员工管理', icon: 'Postcard' },
    { path: '/hr/attendance-report', label: '考勤报表', icon: 'Histogram' },
    { path: '/hr/payroll', label: '薪酬核算', icon: 'Money' },
    { path: '/hr/performance', label: '绩效管理', icon: 'TrendCharts' },
    { path: '/hr/approvals', label: '审批中心', icon: 'Checked' },
    { path: '/hr/administration', label: '行政资产', icon: 'OfficeBuilding' },
  ],
};
